name: image2towny
version: 0.1
api-version: 1.13
main: com.realmtiel.image2towny.Image2Towny
depend: [Towny]

commands:
  imgtowny:
    description: Image2Towny commands
    usage: /imgtowny
    permission: imgtowny
